# Generated by Django 5.0.1 on 2024-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='covers')),
            ],
        ),
    ]
