# Generated by Django 5.0.1 on 2024-04-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_uploads', '0002_alter_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('bg_color', models.CharField(max_length=20)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_uploads.movie')),
            ],
        ),
    ]
